### ISSUE TITLE
Crash when rendering an array of elements

### ISSUE THREAD

**Issue by satya164** [zamotany/react-stream-renderer#23]
The following code will crash the component:

```js
export default class Test extends React.Component {
  state = {
    elements: [],
  };

  componentDidMount() {
    setInterval(() => this.setState({ elements: ['a'] }), 1000);
  }

  render() {
    return (
      <Text>
        {this.state.elements.map((e, i) => <Text key={i}>{e}</Text>)}
        <Text>Placing text here crashes it after a sec</Text>
      </Text>
    );
  }
}
```

What's strange is, the following won't crash:

```js
<Text>
  <Text>Placing text here crashes it after a sec</Text>
  {this.state.elements.map((e, i) => <Text key={i}>{e}</Text>)}
</Text>
```

The error printed in the console is:

```
The above error occurred in the <CHUNK_NODE> component:
    in CHUNK_NODE (created by Text)
    in Text
    in CHUNK_NODE (created by Text)
    in Text
    in Test
```

I did some digging and it comes from `invalidateParent()` method in `ChunkNode`, where `this.parent.invalidateParent()` fails due to parent being undefined.

The issue surfaced after this was added https://github.com/zamotany/react-stream-renderer/commit/7a24053d1fcff44c23ca6d02d80e7f176deb4c8c#diff-d326ff250583ba58a86209fb780cda69R68

**Comment by zamotany** [comment]
When `Text` component looks like this:
```js
export default function Text(props: Props) {
  const { children } = props;
  return (
    <Chunk {...getPositionPros(props)}>
      {children}
    </Chunk>
  );
}
```

`a` from `this.state.elements` never gets rendered (no crashes), which only confirms my assumption that this array (`[<Text>a<Text>]`) never gets attached to the parent node.
This would also explain why the crash itself occurs - if the nodes from array are never attached to parent and they change `invalidateParent` will crash at some point, because the will be no `parent` property assigned.
